### PR TITLE
Adapt deployment for python 2 and 3

### PR DESCRIPTION
**Pull request by joncinque**
Following the same logic as with the new flags `with-python2` and `with-python3` this adds extra directories to build and push the python 2 and python 3 versions of quickfix.  To keep the packages separate, they will need to be uploaded separately, one as requiring exactly version 2.7.*, and another one requiring version >= 3.5.  It makes things slightly more tedious, but this way people can install the package easily from pypi regardless of their environment.  There were a few other fixes needed in order to get things to compile and run.  Let me know if you have any questions.

### CODE REVIEW

**Comment by figar284** [comment]
Any updates on when this will be integrated.  I would love to be able to install quickfix using pip in a python 3 environment.

**Comment by joncinque** [comment]
I'll check with Oren to see what's going on.

**Comment by alexandrul** [comment]
Is there any chance of providing wheels for 64-bit windows (at least for py3)?

**Comment by t3476** [comment]
Any progress? This is important since python 2 is deprecated by some of the large and mature projects, Django and numpy.

**Comment by joncinque** [comment]
Looks like Oren took care of it, so I'll withdraw this.

**Comment by figar284** [comment]
Does this mean version 1.15 (with support for Python 3) will soon be released on pypi?

**Comment by orenmnero** [comment]
Yes. I think I solved the python2 / python3 simultaneous distribution. Just finalizing the general release.

**Pull request closed without merging**
